#!/bin/bash


curl 'https://echo24.cz/' \
  -H 'authority: echo24.cz' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: isLogged=false; bezreklam=true' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-gpc: 1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36' \
  --compressed > ~/.tmp/temp.html

clear

echo ""
cat ~/.tmp/temp.html | pup 'h3.articleNew-default__title' | grep -v "h3" | grep -v "/a" | grep -v "itemprop" | sed G

rm ~/.tmp/temp.html

echo ""
echo ""

while true; do
    read -p "  Jít na echo? " yn
    case $yn in
        [Yy]* ) brave echo24.cz; break;;
        [Nn]* ) exit;;
        * ) echo "yes or no";;
    esac
done

#echo"$thepage" | pup 'h3.articleNew-default__title'
